# -*- coding: utf-8 -*-
"""IterativeDesignPathProject_DPMND_OtavioBastos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wiaFrKpdzkS-dFu-uFcsVe9WkDmUdzQW

# Applying Iterative Design Principles to a Live Product
Otávio Leite Bastos

Data Product Management Nanodegree

Udacity

## Data Exploration

### Mounting Google Drive
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""### Reading Data"""

import pandas as pd

events_df = pd.read_csv('/content/drive/MyDrive/DataProductManagerUdacityData/IterativeDesignPathProject/Flyber_event_logs.csv')

"""### Exploring Data"""

events_df.head()

events_df["date"] = pd.to_datetime(events_df["event_time"])

events_df.columns

events_df.age.unique()

events_df.experiment_group.unique()

events_df.user_neighborhood.unique()

events_df.event_type.unique()

events_df.sort_values(by="date").date.unique()

"""*We can see that all events in the dataset take place in the same week simultaneously. A A/B/n, or a Multivariate Test, was performed.*"""

len(events_df)

len(events_df.session_uuid.unique())/len(events_df.user_uuid.unique())

len(events_df.user_uuid.unique())

"""*On average, roughly 1.6 sessions per users, so we cannot use event_uuid for funnel purposes, we should go with session_uuid.*

## Overall Conversion Impact of the Experiment
"""

def get_funnel_data(df):
  list_experiments = df.experiment_group.unique()
  for experiment in list_experiments:
    print('Experiment:', experiment)
    # ['open', '#_of_users', 'search', 'begin_ride'
    print('Count Event - Open:', len(df[(df.experiment_group == experiment) & (df.event_type == 'open')].session_uuid.unique()))
    print('Count Event - Search:', len(df[(df.experiment_group == experiment) & (df.event_type == 'search')].session_uuid.unique()))
    print('Count Event - Number of Users:', len(df[(df.experiment_group == experiment) & (df.event_type == '#_of_users')].session_uuid.unique()))
    print('Count Event - Begin Ride:', len(df[(df.experiment_group == experiment) & (df.event_type == '#_of_users')].session_uuid.unique()))

get_funnel_data(events_df)

"""## User Research Data"""

interview_df = pd.read_csv('/content/drive/MyDrive/DataProductManagerUdacityData/IterativeDesignPathProject/Flyber User Interviews.csv')

interview_df

interview_df.columns

len(interview_df)

"""## References

https://medium.com/multiplyai/user-conversion-funnel-9d957ce3e80c
"""